services:
  app:
    container_name: ordent
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - ordent

  mysql:
    container_name: ordent-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - ordent
    volumes:
      - /home/ladyhana/Documents/codes/mysql-storage:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p${DB_PASSWORD} -e 'SELECT 1;'"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  ordent: